# This is a boilerplate parameters config generated for pipeline 'xgboost_training_day'
# using Kedro 0.19.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.12/configuration/parameters.html

training_params:
  n_estimators: 80
  max_depth: 5
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  colsample_bynode: 0.8
  gamma: 0.0
  reg_alpha: 0.0
  reg_lambda: 1.0
  min_child_weight: 1
  booster: gbtree
  random_state: 42

validate_params:
  n_splits: 5
  shuffle: true
  random_state: 42

plots_params: 
  plot_repo: data/08_final_models/xgboost_day/plots
  n_days: 3
  random_seed: 42
