# This is a boilerplate parameters config generated for pipeline 'train_tft'
# using Kedro 0.19.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.12/configuration/parameters.html

prepare_tft_data:
  series_id: France
    # columns_to_drop:
    #   - colonne1
    #   - colonne2

tsdataset_tft:
  test_cutoff_years: 1
  val_duration_years: 1
  max_encoder_length: 288
  max_prediction_length: 48

  known_reals:
    - time_idx
    - temperature
    - is_vacation

  unknown_reals:
    - Consommation
    - sunshine_duration

  known_categoricals:
    - weekday
    - month
    - season

  unknown_categoricals: []

  static_reals: []
  static_categoricals: []

train_tft:
  learning_rate: 0.001
  hidden_size: 128
  attention_head_size: 4
  dropout: 0.1
  hidden_continuous_size: 64
  output_size: 7
  loss: QuantileLoss

  max_epochs: 20
  batch_size: 64
  accelerator: gpu
  devices: 1
  precision: 32-true
  gradient_clip_val: 0.1

  use_early_stopping: true
  early_stopping_monitor: val_loss
  early_stopping_patience: 5
  early_stopping_mode: min

  use_checkpoint: true

  log_dir: data/08_final_models/tft/logs
  checkpoint_dir: data/08_final_models/tft/checkpoints

  seed: 42

evaluate_tft:
  batch_size: 256
