# This is a boilerplate parameters config generated for pipeline 'xgboost_training_day'
# using Kedro 0.19.12.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.12/configuration/parameters.html

training_params:
  n_estimators: 71
  max_depth: 3
  learning_rate: 0.12320583647301046
  subsample: 0.9484964775665343
  colsample_bytree: 0.5103868009619887
  colsample_bynode:  0.7472349189960654
  gamma: 1.82596849831038
  reg_alpha: 0.02686899293953963
  reg_lambda: 0.007216440628526577
  min_child_weight: 13
  booster: gbtree
  random_state: 42

plots_params: 
  plot_repo: data/07_model_output/eco2mix/xgboost/day/plots
  n_days: 3
  random_seed: 42
